### ISSUE TITLE
Initial Feature Ideas

### ISSUE THREAD

**Issue by CheesecakeCG** [Mill-Creek-First-Robotics/steel-talon-discord-bot#1]
Suggest feature ideas

**Comment by Evanator331** [comment]
A reminder bot that tells us to work on programming each week

**Comment by Evanator331** [comment]
A gambling bot

**Comment by GPIOctapus** [comment]
Reminder input system:
-Heads can set a reminder for a date (example "#setremind *insert stuff here*")
-will mention role about reminder
-should post in appropriate channel (programming in programming, ect)

**Comment by CheesecakeCG** [comment]
- [ ] Normie Fornite Memes
- [ ] r/Wholesome Memes
- [ ] Add role
- [ ] Chat bot
- [ ] Economy/Points for talking and working on project
- [ ] Remind101 Forwarding

**Comment by mailprahs** [comment]
Censor bot
Censors messages with swears or certain words

**Comment by Snaekadoodle** [comment]
> Censor bot
> Censors messages with swears or certain words

make a command with a random number generator that can substitute the word that you would normally swear with (like shloop, or fbabble)
